spring:
  ##============================================================================
  ## datasource configuration
  ##============================================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

##============================================================================
## mybatis configuration
##============================================================================
mybatis:
  connector-location: C:/Users/lixl/.m2/repository/mysql/mysql-connector-java/8.0.12/mysql-connector-java-8.0.12.jar
  jdbcConnection:
    driverClass: com.mysql.cj.jdbc.Driver
    connectionURL: jdbc:mysql://localhost:3306/test?useSSL=false
    userId: root
    password: root
  entity-location: ../manager/src/generated/java
  entity-package: com.example.entity
  mapper-location: ../dao/src/generated/java
  mapper-package: com.example.mybatis.mapper
















